# Generated by Django 4.2.1 on 2023-06-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
