# Generated by Django 4.2.1 on 2023-06-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpro', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='audio_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=20),
        ),
    ]
