# Generated by Django 4.2.1 on 2023-06-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpro', '0004_image_audio_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='audio_type',
            new_name='type',
        ),
    ]
