# Generated by Django 4.2.1 on 2023-06-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpro', '0005_rename_audio_type_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
